import crypto from "node:crypto";

/** SHA-256 for downloaded/generated bytes. Unlike the textual identity helper,
 * this preserves Buffer/Uint8Array bytes exactly for auditable provenance. */
export function sha256Bytes(value) {
  const bytes = Buffer.isBuffer(value)
    ? value
    : value instanceof Uint8Array
      ? Buffer.from(value.buffer, value.byteOffset, value.byteLength)
      : Buffer.from(String(value), "utf8");
  return crypto.createHash("sha256").update(bytes).digest("hex");
}
